name: assure
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_displaymode: ^0.6.0
  freezed_annotation: ^2.2.0
  grpc: ^3.1.0
  json_annotation: ^4.8.1
  protobuf: ^2.0.0
  equatable: ^2.0.5
  get_it: ^7.6.0
  flex_color_scheme: ^7.0.5
  intl: ^0.17.0
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        
flutter_intl:
  main_locale: ru
  enabled: true